src/dresden23/model/Car.java
package dresden23.model;

// for date datatype

import dresden23.model.exception.IntervalConstraintViolation;
import dresden23.model.exception.MandatoryValueConstraintViolation;
import dresden23.model.exception.UniquenessConstraintViolation;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.model.SelectItem;
import javax.persistence.RollbackException;
import javax.persistence.*;
import javax.transaction.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

//import com.sun.istack.internal.NotNull;
/* The annotation @Entity designates a class as an entity class implying that the instances of this class will be stored
 persistently. --> Java Persistence API (JPA)
 */
@Entity
@Table( name="cars")
/*
4.4. Define the managed beans needed in facelets


JavaBean classes, including entity classes, can be used for creating 'managed beans' with the help of the @ManagedBean
 annotation, which allows defining the name of a variable for accessing the created bean in the view code, typically
 in an EL expression. In our example app, we want to access a Car bean as well as a CarController bean, therefore both
  classes have to be annotated as follows:

  Notice how a lifetime scope can be specified for a managed bean with a scope annotation. In our example the book bean
   is @RequestScoped, this means the instance exists as long as the HTTP request and the associated response are being
   processed. The bookCtrl bean is @SessionScoped, which means it is created when the session starts, and destroyed when
    the session is closed. Other scopes are available, but in our example we only need these two.

 */
@RequestScoped @ManagedBean( name="car") @ViewScoped

public class Car {
    //Mandatory, ID
    @Id
    @NotNull ( message="A carId is required!")
    private Integer carId;
    @Column( nullable=false)
    @NotNull ( message="A Car name is required!")
    private String name;
    @Column( nullable=false)
    @NotNull ( message="A car ProductionYear is required!")
    private Date productionYear;
    @Column( nullable=false)
    @NotNull ( message="A value for horsepower is required!")
    private Integer power;
    @Column( nullable=false)
    @NotNull ( message="A Status for the car is required!")
    @Enumerated( EnumType.STRING)
    private StatusEL status;
    @Column( nullable=false)
    @NotNull ( message="A Price for the car is required!")
    @Min( value=0, message="Price must be > 0!")
    private Integer price;
    @ManyToMany( fetch=FetchType.EAGER)
    @JoinTable( name="cars_cartypes",
            joinColumns={ @JoinColumn( name="car_carid") },
            inverseJoinColumns = { @JoinColumn( name="cartype_cartypeid") })
    private Set<CarType> cartypes;
    // default constructor (required for entity classes)
    public Car() {}
    // constructor
    public Car(Integer carId, String name, Date productionYear, Integer power, StatusEL status, Integer price,
               Set<CarType> cartypes) {
        this.setCarId(carId);
        this.setName(name);
        this.setProductionYear(productionYear);
        this.setPower(power);
        this.setStatus(status);
        this.setPrice(price);
        this.setCarTypes(cartypes);
    }
    // getter and setter methods
    public Integer getCarId() {
        return carId;
    }
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Date getProductionYear() {
        return productionYear;
    }
    public void setProductionYear(Date productionYear) {
        this.productionYear = productionYear;
    }
    public Integer getPower() {
       return power;
    }
    public void setPower(Integer power) {
        this.power = power;
    }
    public StatusEL getStatus() {
        return status;
    }
    public void setStatus(StatusEL status) {
        this.status = status;
    }
    public Integer getPrice() {
        return price;
    }
    public void setPrice(Integer price) {
        this.price = price;
    }

    public Set<CarType> getCarTypes() {
        return cartypes;
    }

    public void setCarTypes( Set<CarType> cartypes) {
        Set<CarType> oldCarTypes = this.cartypes != null ? new HashSet<CarType>(
                this.cartypes) : null;
        // remove old cartypes
        if ( oldCarTypes != null) {
            for ( CarType c : oldCarTypes) {
                this.removeCarType( c);
            }
        }
        // add new cartypes
        if ( cartypes != null) {
            for ( CarType c : cartypes) {
                this.addCarType( c);
            }
        } else {
            if ( this.cartypes != null) {
                this.cartypes.clear();
            }
        }
    }

    public void addCarType( CarType cartype) {
        if ( this.cartypes == null) {
            this.cartypes = new HashSet<CarType>();
        }
        if ( !this.cartypes.contains( cartype)) {
            this.cartypes.add( cartype);
            cartype.addCartypedCar( this);
        }
    }

    public void removeCarType( CarType cartype) {
        if ( this.cartypes != null && cartype != null
                && this.cartypes.contains( cartype)) {
            this.cartypes.remove( cartype);
            cartype.removeCartypedCar( this);
        }
    }

    /**
     * Return the serialized cartype names used in the JSF views.
     *
     * @return serialized cartype names for this book.
     */
    public String getCarTypeNames() {
        String result = "";
        Integer i = 0, n = 0;
        if ( this.cartypes != null) {
            n = this.cartypes.size();
            for ( CarType cartype : this.cartypes) {
                result += cartype.getName();
                if ( i < n - 1) {
                    result += ", ";
                }
                i++;
            }
        }
        return result;
    }


//    /**
//     * Create a human readable serialization.
//     */
//    public String toString() {
//        return "{ carId: '" + this.carId + "', Name:'" + this.name + "', ProductionproductionYear: '"
//                + this.productionYear + "', Power: '" +this.power + "' Status: '"+ this.status + "' price: '"
//                + this.price + "}";
//    }

    /**
     * Create a human readable serialisation.
     *
     */
    public String toString() {
        String result = "{ carid: '" + this.carId + "', name:'" + this.name
                + "', productionYear: " + this.productionYear + ", publisher: "
                + "', Power: '" +this.power + "' Status: '"+ this.status + "' price: '" + this.price
                + ", cartypes: [";
        if ( this.cartypes != null) {
            Integer i = 0, n = this.cartypes.size();
            for ( CarType c : this.cartypes) {
                result += "'" + c.getName() + "'";
                if ( i < n - 1) {
                    result += ", ";
                }
                i++;
            }
        }
        result += "]}";
        return result;
    }

    @Override
    public boolean equals( Object obj) {
        if (obj instanceof Car) {
            Car car = (Car) obj;
            return ( this.carId.equals( car.carId));
        } else return false;
    }


    /**
     * Create and return the set of items containing the statuses which are
     * available for the car. The available languages are the literals of
     * LanguageEL enumeration.
     *
     * @return the set of status items
     */
    public SelectItem[] getStatusItems() {
        SelectItem[] items = new SelectItem[StatusEL.values().length];
        Integer i = 0;
        for ( StatusEL status : StatusEL.values()) {
            items[i++] = new SelectItem( status.name(), status.getLabel());
        }
        return items;
    }



    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws UniquenessConstraintViolation
     */
    public static void checkCarIdAsId( EntityManager em, Integer carId)
            throws UniquenessConstraintViolation,
            IntervalConstraintViolation {
        if (carId < 0) {
            throw new IntervalConstraintViolation(
                    "CarId must be at least 0");
        } else {
            Car car = Car.retrieve( em, carId);
            // car was found, uniqueness constraint validation failed
            if ( car != null) {
                throw new UniquenessConstraintViolation(
                    "There is already a car record with this carId!");
            }
        }
    }

    public static void checkName( EntityManager em, String name)
            throws MandatoryValueConstraintViolation {
        if (name == null) {
            throw new MandatoryValueConstraintViolation(
                    "Car Name is mandatory");
        }
    }



    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkProductionYear( EntityManager em, Date productionYear)
            throws IntervalConstraintViolation, ParseException {
        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
        Date datecheck = date.parse("01/01/1886");
        if ( productionYear.before(datecheck)) {
            throw new IntervalConstraintViolation(
                    "The car cannot be produced before 1886");
        }
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the

web/views/cars/create.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
<!--      <h:form id="createCarForm" styleClass="pure-form pure-form-aligned" >-->
      <h:form id="createCarForm" styleClass="clearfix" >
        <h:panelGrid id="carPanel" columns="3">
          <h:outputLabel for="carId" value="CarId: " />
            <h:inputText id="carId" value="#{car.carId}"
                         validator="#{carCtrl.checkCarIdAsId}" />
            <h:message for="carId" errorClass="error" />
          <h:outputLabel for="name" value="Name: " />
            <h:inputText id="name" value="#{car.name}"
                         validator="#{carCtrl.checkName}" />
            <h:message for="name" errorClass="error" />
          <h:outputLabel for="productionyear" value="Productionyear: " />
            <h:inputText id="productionyear" p:type="date" value="#{car.productionYear}">
              <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"/>
            </h:inputText>
            <h:message for="productionyear" errorClass="error" />
          <h:outputLabel for="power" value="Power: " />
            <h:inputText id="power" value="#{car.power}"
                         validator="#{carCtrl.checkPower}" />
            <h:message for="power" errorClass="error" />
          <h:outputLabel for="status" value="Status" />
            <h:selectOneMenu id="status"
                             value="#{car.status}">
              <f:selectItem itemValue="" itemLabel="---" />
              <f:selectItems value="#{car.statusItems}" />
            </h:selectOneMenu>
          <h:outputLabel for="price" value="Price: " />
            <h:inputText id="price" value="#{car.price}" />
            <h:message for="price" errorClass="error" />
          <h:outputLabel for="cartypes" value="CarTypes:" />
          <h:selectManyListbox id="cartypes" value="#{car.carTypes}">
            <f:selectItems value="#{cartypeCtrl.carTypes}" var="ct"
                           itemLabel="#{ct.name}" itemValue="#{ct}" />
            <f:converter converterId="dresden23.model.converter.CarTypeConverter" />
          </h:selectManyListbox>
          <h:message for="cartypes" errorClass="error" />
        </h:panelGrid>
        <h:panelGroup id="standardCarPanel">  
          <h:commandButton value="Create"
            action="#{carCtrl.create( car.carId, car.name, car.productionYear, car.power, car.status, car.price,
             car.carTypes )}" />
        </h:panelGroup>
        
<!--        <h:panelGroup id="textCarPanel">  -->
<!--          <h:panelGrid rendered="#{viewScope.carTypeVal == 'TEXTBOOK'}" columns="3">-->
<!--            <h:outputLabel for="subjectArea" value="Subject area: " />-->
<!--            <h:inputText id="subjectArea" value="#{textCar.subjectArea}"/>-->
<!--            <h:message for="subjectArea" errorClass="error" />-->
<!--          </h:panelGrid>-->
<!--          <h:commandButton value="Create" rendered="#{viewScope.carTypeVal == 'TEXTBOOK'}"-->
<!--            action="#{textCarCtrl.add( car.carId, car.title, car.year, textCar.subjectArea)}" />-->
<!--        </h:panelGroup>-->
<!--        -->
<!--        <h:panelGroup id="biographyCarPanel">-->
<!--          <h:panelGrid rendered="#{viewScope.carTypeVal == 'BIOGRAPHY'}" columns="3">-->
<!--            <h:outputLabel for="about" value="About: " />-->
<!--            <h:inputText id="about" value="#{biographyCar.about}"/>-->
<!--            <h:message for="about" errorClass="error" />-->
<!--          </h:panelGrid>-->
<!--          <h:commandButton value="Create" rendered="#{viewScope.carTypeVal == 'BIOGRAPHY'}"-->
<!--            action="#{biographyCtrl.add( car.carId, car.title, car.year, biographyCar.about)}" />-->
<!--        </h:panelGroup>-->
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/cars/delete.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="deleteCarForm" styleClass="pure-form pure-form-aligned">
        <h:panelGrid columns="2">
          <h:outputLabel for="selectCar" value="Select Car: " />
          <h:selectOneMenu id="selectCar" value="#{car.carId}">
            <f:selectItems value="#{carCtrl.cars}" var="c"
              itemValue="#{c.carId}" itemLabel="#{c.name}" />
          </h:selectOneMenu>
        </h:panelGrid>
        <h:commandButton value="Delete"
          action="#{carCtrl.destroy( car.carId)}" />
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/cars/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h2>Manage Car entries:</h2>
      <h:button value="List all cars" outcome="listAll" />
      <h:button value="Add a new Car" outcome="create" />
      <h:button value="Update a car" outcome="update" />
      <h:button value="Delete a car" outcome="delete" />
      <h:button value="Main menu" outcome="/views/app/index" />
    </ui:define>
  </ui:composition>
</html>

web/views/cars/listAll.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:dataTable value="#{carCtrl.cars}" var="c">
        <h:column>
          <f:facet name="header">CarId</f:facet>
            #{c.carId}
        </h:column>
        <h:column>
          <f:facet name="header">Name</f:facet>
            #{c.name}
          </h:column>
        <h:column>
          <f:facet name="header">ProductionYear</f:facet>
            #{c.productionYear}
        </h:column>
        <h:column>
          <f:facet name="header">Power</f:facet>
          #{c.power}
        </h:column>
        <h:column>
          <f:facet name="header">Status</f:facet>
          #{c.status}
        </h:column>
        <h:column>
          <f:facet name="header">Price</f:facet>
          #{c.price}
        </h:column>
        <h:column>
          <f:facet name="header">CarTypes</f:facet>
          #{c.carTypes}
        </h:column>
      </h:dataTable>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/cars/update.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="createCarForm" styleClass="pure-form pure-form-aligned">
        <h:panelGrid id="carPanel" columns="3">
          <h:outputLabel for="selectCar" value="Select car: " />
          <h:selectOneMenu id="selectCar" value="#{car.carId}">
            <f:selectItem itemValue="" itemLabel="---" />
            <f:selectItems value="#{carCtrl.cars}" var="c"
              itemValue="#{c.carId}" itemLabel="#{c.name}" />
            <f:ajax listener="#{carCtrl.refreshObjects(car)}"
              render="carId name productionyear power status price cartypes" />
          </h:selectOneMenu>
          <h:message for="selectCar" />
          <h:outputLabel for="carId" value="CarId: " />
          <h:outputText id="carId" value="#{car.carId}" />
          <h:message for="carId" />
          <h:outputLabel for="name" value="Name: " />
          <h:inputText id="name" value="#{car.name}" />
          <h:message for="name" errorClass="error" />
          <h:outputLabel for="productionyear" value="Productionyear: " />
          <h:inputText id="productionyear" p:type="date" value="#{car.productionYear}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"/>
          </h:inputText>
          <h:message for="productionyear" errorClass="error" />
          <h:outputLabel for="power" value="Power: " />
          <h:inputText id="power" p:type="number" value="#{car.power}" />
          <h:message for="power" errorClass="error" />

          <h:outputLabel for="status" value="Special type: " />
          <c:set var="selectedStatus" value="#{car.status}"/>
          <h:selectOneMenu id="status" value="#{selectedStatus}">
            <f:selectItem itemLabel="---"/>
            <f:selectItems value="#{car.statusItems}" />
          </h:selectOneMenu>
          <h:message for="status" errorClass="error" />
          <h:outputLabel for="price" value="Price: " />
          <h:inputText id="price" p:type="number" value="#{car.price}" />
          <h:message for="price" errorClass="error" />
          <h:outputLabel for="cartypes" value="CarTypes:" />
          <h:selectManyListbox id="cartypes" value="#{car.carTypes}" >
            <f:selectItems value="#{cartypeCtrl.carTypes}" var="ct"
                           itemLabel="#{ct.name}" itemValue="#{ct}" />
            <f:converter converterId="dresden23.model.converter.CarTypeConverter" />
          </h:selectManyListbox>
          <h:message for="cartypes" errorClass="error" />
        </h:panelGrid>
        
        <h:panelGroup id="standardCarPanel">
          <h:commandButton value="Update"
            action="#{carCtrl.update( car.carId, car.name, car.productionYear, car.power, car.status, car.price,
             car.carTypes)}" />
        </h:panelGroup>
<!--        -->
<!--        <h:panelGroup id="textCarPanel">  -->
<!--          <h:panelGrid rendered="#{selectedCarType == 'TEXTBOOK'}" columns="3">-->
<!--            <h:outputLabel for="subjectArea" value="Subject area: " />-->
<!--            <h:inputText id="subjectArea" value="#{textCar.subjectArea}"/>-->
<!--            <h:message for="subjectArea" errorClass="error" />-->
<!--          </h:panelGrid>-->
<!--          <h:commandButton value="Update" rendered="#{selectedCarType == 'TEXTBOOK'}"-->
<!--            action="#{textCarCtrl.update( car.carId, car.title, car.productionyear, textCar.subjectArea)}" />-->
<!--        </h:panelGroup>-->
<!--        -->
<!--        <h:panelGroup id="biographyCarPanel">  -->
<!--          <h:panelGrid rendered="#{selectedCarType == 'BIOGRAPHY'}" columns="3">-->
<!--            <h:outputLabel for="about" value="About: " />-->
<!--            <h:inputText id="about" value="#{biographyCar.about}"/>-->
<!--            <h:message for="about" errorClass="error" />-->
<!--          </h:panelGrid>-->
<!--          <h:commandButton value="Update" rendered="#{selectedCarType == 'BIOGRAPHY'}"-->
<!--            action="#{biographyCtrl.update( car.carId, car.title, car.productionyear, biographyCar.about)}" />-->
<!--        </h:panelGroup>-->
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>