src/dresden23/model/OfferOfTheWeek.java
package dresden23.model;

import com.sun.istack.internal.NotNull;
import dresden23.model.exception.IntervalConstraintViolation;
import dresden23.model.exception.MandatoryValueConstraintViolation;
import dresden23.model.exception.UniquenessConstraintViolation;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.persistence.*;
import javax.persistence.RollbackException;
import javax.transaction.*;
import java.util.Date;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "offeroftheweeks")
@RequestScoped
@ViewScoped
@ManagedBean( name="offeroftheweek")

public class OfferOfTheWeek {
    @NotNull @Id private Integer offerId;
    @NotNull private String name;
    @NotNull private Date datefrom;
    @NotNull private Date dateto;
    @NotNull private Integer discount;
    @OneToMany( fetch=FetchType.LAZY)
    private Set<Car> cars;
    //default constructor
    public OfferOfTheWeek() {}
    //constructor
    public OfferOfTheWeek( Integer offerId, String name, Date datefrom, Date dateto, Integer discount, Set<Car> cars) {
        this.setOfferId(offerId);
        this.setName(name);
        this.setDateFrom(datefrom);
        this.setDateTo(dateto);
        this.setDiscount(discount);
        this.setCars(cars);
    }
    public Integer getOfferId() {
        return offerId;
    }
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateFrom() {
        return datefrom;
    }
    public void setDateFrom(Date datefrom) {
        this.datefrom = datefrom;
    }
    public Date getDateTo() {
        return dateto;
    }
    public void setDateTo(Date dateto) {
        this.dateto = dateto;
    }
    public Integer getDiscount() {
        return discount;
    }
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    public Set<Car> getCars() {
        return cars;
    }

    public void setCars( Set<Car> cars) {
        this.cars = cars;
    }

    /**
     * Return the serialized car names used in the JSP views.
     *
     * @return a serialized car names for this OfferofTheWeek.
     */
    public String getCarNames() {
        String result = "";
        int i = 0, n = 0;
        if ( this.cars != null) {
            n = this.cars.size();
            for ( Car car : this.cars) {
                result += car.getName();
                if ( i < n - 1) {
                    result += ", ";
                }
                i++;
            }
        }
        return result;
    }

    /**
     * Create a human readable serialization.
     */
    public String toString() {
        String result = "{ OfferId: '" + this.offerId + "', Name:'" + this.name
                + "', datefrom: " + this.datefrom + ", dateto: "+ this.dateto + " discount: "+ this.discount;
        result += ", cars: [";
        if ( this.getCars() != null) {
            int i = 0, n = this.getCars().size();
            for ( Car c : this.getCars()) {
                result += "'" + c.getName() + "'";
                if ( i < n - 1) {
                    result += ", ";
                }
                i++;
            }
        }
        result += "}";
        return result;
    }


    @Override
    public boolean equals( Object obj) {
        if (obj instanceof Car) {
            OfferOfTheWeek offer = (OfferOfTheWeek) obj;
            return ( this.offerId.equals( offer.offerId));
        } else return false;
    }


    // CRUD data management methods
    public static void create( EntityManager em, UserTransaction ut, Integer offerId, String name, Date datefrom,
                               Date dateto, Integer discount, Set<Car> cars)
            throws NotSupportedException, SystemException, IllegalStateException,
            SecurityException, HeuristicMixedException, HeuristicRollbackException,
            RollbackException, EntityExistsException, javax.transaction.RollbackException {
        ut.begin();
        OfferOfTheWeek offer = new OfferOfTheWeek( offerId, name, datefrom, dateto, discount, cars);
        em.persist( offer);
        if ( cars != null) {
            for ( Car c : cars) {
                em.merge( c);
            }
        }
        ut.commit();
        System.out.println( "Offer.add: the Offer " + offer + " was saved.");
    }

    public static List<OfferOfTheWeek> retrieveAll(EntityManager em) {
        Query query = em.createQuery( "SELECT o FROM OfferOfTheWeek o", OfferOfTheWeek.class);
        List<OfferOfTheWeek> offers = query.getResultList();
        return offers;
    }

    public static OfferOfTheWeek retrieve(EntityManager em, Integer offerId) {
        OfferOfTheWeek offer = em.find( OfferOfTheWeek.class, offerId);
        if ( offer != null) {
            System.out.println( "OfferOfTheWeek.retrieve: loaded offer " + offer);
        }
        return offer;
    }

    public static void update( EntityManager em, UserTransaction ut, Integer offerId, String name, Date datefrom, Date dateto,
                               Integer discount, Set<Car> cars)
            throws NotSupportedException, SystemException, IllegalStateException,
            SecurityException, HeuristicMixedException, HeuristicRollbackException,
            RollbackException, javax.transaction.RollbackException {
        ut.begin();
        OfferOfTheWeek offer = em.find(OfferOfTheWeek.class, offerId);
        if (offer == null) {
            throw new EntityNotFoundException("The Offer with OfferId = " + offer
                    + " was not found!");
        }
        Set<Car> oldCars = offer.getCars();
        if (name != null && !name.equals(offer.name)) {
            offer.setName(name);
        }
        if (datefrom != null && !datefrom.equals(offer.datefrom)) {
            offer.setDateFrom(datefrom);
        }
        if (dateto != null && !dateto.equals(offer.dateto)) {
            offer.setDateTo(dateto);
        }
        if (discount != null && !discount.equals(offer.discount)) {
            offer.setDiscount(discount);
        }
        if (cars != null && !cars.equals(offer.cars)) {
            offer.setCars(cars);
        }
        // merge managed entities in the memory, also update the cached versions
        // and the entity changes are reflected next time when used
        if (oldCars != null) {
            for (Car c : oldCars) {
                em.merge(c);
            }
        }
        if (cars != null) {
            for (Car c : cars) {
                em.merge(c);
            }
        }
        ut.commit();
        System.out.println("Offer.update: the offer " + offer + " was updated.");
    }

    public static void delete( EntityManager em,
                               UserTransaction ut, Integer offerId) throws Exception {
        ut.begin();
        OfferOfTheWeek offer = em.find( OfferOfTheWeek.class, offerId);
        em.remove( offer);
        ut.commit();
    }
    public static void clearData( EntityManager em,
                                  UserTransaction ut) throws Exception {
        ut.begin();
        Query deleteStatement = em.createQuery( "DELETE FROM OfferOfTheWeek ");
        deleteStatement.executeUpdate();
        ut.commit();
    }

    /**
     * Check for the offerId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given offerId value.
     *
     * @throws UniquenessConstraintViolation
     */
    public static void checkOfferIdAsId( EntityManager em, Integer offerId)
            throws UniquenessConstraintViolation,
            IntervalConstraintViolation {
        if (offerId < 0) {
            throw new IntervalConstraintViolation(
                    "OfferId must be at least 0");
        } else {
            Car car = Car.retrieve( em, offerId);
            // car was found, uniqueness constraint validation failed
            if ( car != null) {
                throw new UniquenessConstraintViolation(
                        "There is already a offer record with this offerId!");
            }
        }
    }

    public static void checkName( EntityManager em, String name)
            throws MandatoryValueConstraintViolation {
        if (name == null) {
            throw new MandatoryValueConstraintViolation(
                    "Offer Name is mandatory");
        }
    }

    public static void checkDateFrom( EntityManager em, Date dateFrom)
            throws MandatoryValueConstraintViolation {
        if (dateFrom == null) {
            throw new MandatoryValueConstraintViolation(
                    "Date From is mandatory");
        }
    }

    public static void checkDateTo( EntityManager em, Date dateTo)
            throws MandatoryValueConstraintViolation {
        if (dateTo == null) {
            throw new MandatoryValueConstraintViolation(
                    "Date To is mandatory");
        }
    }

    public static void checkDiscount( EntityManager em, Integer discount)
            throws MandatoryValueConstraintViolation {
        if (discount == null) {
            throw new MandatoryValueConstraintViolation(
                    "Discount is mandatory");
        }
    }

//    public static void generateTestData( EntityManager em,
//                                         UserTransaction ut) throws Exception {
//        OfferOfTheWeek offer = null;
//        OfferOfTheWeek.clearData( em, ut);  // first clear the books table
//        ut.begin();
//        offer = new OfferOfTheWeek(1,"Offer 1", new Date(2008), new Date(2008), 5000);
//        em.persist( offer);
//        offer = new OfferOfTheWeek(2,"Offer 2", new Date(2008), new Date(2008), 5000);
//        em.persist( offer);
//        offer = new OfferOfTheWeek(3,"Offer 3", new Date(2008), new Date(2008), 6000);
//        em.persist( offer);

web/views/offeroftheweeks/create.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="createOfferOfTheWeekForm" styleClass="clearfix" >
        <h:panelGrid id="offerOfTheWeekPanel" columns="3">
          <h:outputLabel for="offerId" value="OfferId: " />
          <h:inputText id="offerId" value="#{offeroftheweek.offerId}"
                       validator="#{offeroftheweekCtrl.checkOfferIdAsId}" />
          <h:message for="offerId" errorClass="error" />
          <h:outputLabel for="name" value="Name: " />
          <h:inputText id="name" value="#{offeroftheweek.name}"
                       validator="#{offeroftheweekCtrl.checkName}" />
          <h:message for="name" errorClass="error" />
          <h:outputLabel for="datefrom" value="From: " />
          <h:inputText id="datefrom" p:type="date" value="#{offeroftheweek.dateFrom}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"
                               validator="#{offeroftheweekCtrl.checkDateFrom}" />
          </h:inputText>
          <h:message for="datefrom" errorClass="error" />
          <h:outputLabel for="dateto" value="To: " />
          <h:inputText id="dateto" p:type="date" value="#{offeroftheweek.dateTo}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"
                               validator="#{offeroftheweekCtrl.checkDateTo}" />
          </h:inputText>
          <h:message for="dateto" errorClass="error" />
          <h:outputLabel for="discount" value="Discount: " />
          <h:inputText id="discount" value="#{offeroftheweek.discount}"
                       validator="#{offeroftheweekCtrl.checkDiscount}" />
          <h:message for="discount" errorClass="error" />
          <h:outputLabel for="cars" value="Cars:" />
          <h:selectManyListbox id="cars"
                               value="#{offeroftheweek.cars}">
            <f:selectItems value="#{carCtrl.cars}" var="c"
                           itemLabel="#{c.name}" itemValue="#{c}" />
            <f:converter converterId="dresden23.model.converter.CarConverter" />
          </h:selectManyListbox>
          <h:message for="cars" errorClass="error" />

        </h:panelGrid>

        <h:panelGroup id="standardOfferOfTheWeekPanel">
          <h:commandButton value="Create"
                           action="#{offeroftheweekCtrl.create( offeroftheweek.offerId, offeroftheweek.name,
                           offeroftheweek.dateFrom, offeroftheweek.dateTo, offeroftheweek.discount, offeroftheweek.cars )}" />
        </h:panelGroup>
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/offeroftheweeks/delete.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="deleteOfferForm" styleClass="pure-form pure-form-aligned">
        <h:panelGrid columns="2">
          <h:outputLabel for="selectOffer" value="Select offer: " />
          <h:selectOneMenu id="selectOffer" value="#{offeroftheweek.offerId}">
            <f:selectItems value="#{offeroftheweekCtrl.offers}" var="o"
              itemValue="#{o.offerId}" itemLabel="#{o.name}" />
          </h:selectOneMenu>
        </h:panelGrid>
        <h:commandButton value="Delete"
          action="#{offeroftheweekCtrl.destroy( offeroftheweek.offerId)}" />
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/offeroftheweeks/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h2>Manage OfferofTheWeek entries:</h2>
      <h:button value="List all offeroftheweeks" outcome="listAll" />
      <h:button value="Add a new offeroftheweek" outcome="create" />
      <h:button value="Update a offeroftheweek" outcome="update" />
      <h:button value="Delete a offeroftheweek" outcome="delete" />
      <h:button value="Main menu" outcome="/views/app/index" />
    </ui:define>
  </ui:composition>
</html>

web/views/offeroftheweeks/listAll.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:dataTable value="#{offeroftheweekCtrl.offers}" var="o">
        <h:column>
          <f:facet name="header">OfferId</f:facet>
            #{o.offerId}
        </h:column>
        <h:column>
          <f:facet name="header">Name</f:facet>
            #{o.name}
          </h:column>
        <h:column>
          <f:facet name="header">DateFrom</f:facet>
            #{o.dateFrom}
        </h:column>
        <h:column>
<!--          <f:facet name="header">Special type</f:facet>-->
<!--            #{b.getClass().getSimpleName() != 'Book' ? b.getClass().getSimpleName() : ''}-->
          <f:facet name="header">DateTo</f:facet>
          #{o.dateTo}
        </h:column>
        <h:column>
          <f:facet name="header">Discount</f:facet>
          #{o.discount}
        </h:column>
        <h:column>
          <f:facet name="header">Cars</f:facet>
          #{o.carNames}
        </h:column>
      </h:dataTable>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/offeroftheweeks/update.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="createBookForm" styleClass="pure-form pure-form-aligned">
        <h:panelGrid id="offerPanel" columns="3">
          <h:outputLabel for="selectOffer" value="Select offer: " />
          <h:selectOneMenu id="selectOffer" value="#{offeroftheweek.offerId}">
            <f:selectItem itemValue="" itemLabel="---" />
            <f:selectItems value="#{offeroftheweekCtrl.offers}" var="o"
              itemValue="#{o.offerId}" itemLabel="#{o.offerId}" />
            <f:ajax listener="#{offeroftheweekCtrl.refreshObjects(offeroftheweek)}" event="change" execute="@this"
              render="offerId name datefrom dateto discount cars" />
          </h:selectOneMenu>
          <h:message for="selectOffer" />
          <h:outputLabel for="offerId" value="OfferId: " />
          <h:outputText id="offerId" value="#{offeroftheweek.offerId}" />
          <h:message for="offerId" />
          <h:outputLabel for="name" value="Name: " />
          <h:inputText id="name" value="#{offeroftheweek.name}" />
          <h:message for="name" errorClass="error" />
          <h:outputLabel for="datefrom" value="From: " />
          <h:inputText id="datefrom" p:type="date" value="#{offeroftheweek.dateFrom}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"
                               validator="#{offeroftheweekCtrl.checkDateFrom}" />
          </h:inputText>
          <h:message for="datefrom" errorClass="error" />
          <h:outputLabel for="dateto" value="To: " />
          <h:inputText id="dateto" p:type="date" value="#{offeroftheweek.dateTo}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"
                               validator="#{offeroftheweekCtrl.checkDateTo}" />
          </h:inputText>
          <h:message for="dateto" errorClass="error" />
          <h:outputLabel for="discount" value="Discount: " />
          <h:inputText id="discount" value="#{offeroftheweek.discount}"
                       validator="#{offeroftheweekCtrl.checkDiscount}" />
          <h:message for="discount" errorClass="error" />
          <h:outputLabel for="cars" value="Cars:" />
          <h:selectManyListbox id="cars"
                               value="#{offeroftheweek.cars}">
            <f:selectItems value="#{carCtrl.cars}" var="c"
                           itemLabel="#{c.name}" itemValue="#{c}" />
            <f:converter converterId="dresden23.model.converter.CarConverter" />
          </h:selectManyListbox>
          <h:message for="cars" errorClass="error" />
        </h:panelGrid>
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>