src/dresden23/model/Rental.java
package dresden23.model;

import com.sun.istack.internal.NotNull;
import dresden23.model.exception.IntervalConstraintViolation;
import dresden23.model.exception.MandatoryValueConstraintViolation;
import dresden23.model.exception.UniquenessConstraintViolation;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.persistence.RollbackException;
import javax.persistence.*;
import javax.transaction.*;
import java.text.ParseException;
import java.util.Date;
import java.util.List;

@Entity //persistance storage
@Table(name ="rentals") //name of the table storing data
@RequestScoped
@ManagedBean( name="rental")

public class Rental {
    @NotNull @Id private Integer rentalId;
    @NotNull private Date rentaldate;
    @NotNull private Date rentalfrom;
    @NotNull private Date rentalto;
    @NotNull private Integer discount;
    @NotNull private boolean deliverytothepoint;
    private String deliveryaddress;
    @NotNull private Integer total;
    @ManyToOne( fetch=FetchType.EAGER)
    private Car car;
    @ManyToOne ( fetch=FetchType.EAGER)
    private PickUpPoint pickuppoint;
    @ManyToOne ( fetch=FetchType.EAGER)
    private Customer customer;
    // default constructor (required for entity classes)
    public Rental() {}
    // constructor
    public Rental ( Integer rentalId, Date rentaldate, Date rentalfrom, Date rentalto, Integer discount,
                    boolean deliverytothepoint, String deliveryaddress, Integer total, Car car, PickUpPoint pickuppoint,
                    Customer customer) {
        this.setRentalId (rentalId);
        this.setRentaldate(rentaldate);
        this.setRentalfrom (rentalfrom);
        this.setRentalto (rentalto);
        this.setDiscount(discount);
        this.setDeliveryToThePoint(deliverytothepoint);
        this.setDeliveryaddress(deliveryaddress);
        this.setTotal(total);
        this.setCar(car);
        this.setPickuppoint(pickuppoint);
        this.setCustomer(customer);
    }
    public Integer getRentalId() {
        return rentalId;
    }
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }
    public Date getRentaldate() {
        return rentaldate;
    }
    public void setRentaldate(Date rentaldate) {
        this.rentaldate = rentaldate;
    }
    public Date getRentalfrom() {
        return rentalfrom;
    }
    public void setRentalfrom(Date rentalfrom) {
        this.rentalfrom = rentalfrom;
    }
    public Date getRentalto() {
        return rentalto;
    }
    public void setRentalto(Date rentalto) {
        this.rentalto = rentalto;
    }
    public Integer getDiscount() {
        return discount;
    }
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public boolean getDeliveryToThePoint() {
        return deliverytothepoint;
    }
    public void setDeliveryToThePoint(boolean deliverytothepoint) {
        this.deliverytothepoint = deliverytothepoint;
    }
    public String getDeliveryaddress() {
        return deliveryaddress;
    }
    public void setDeliveryaddress(String deliveryaddress) {
        this.deliveryaddress = deliveryaddress;
    }
    public Integer getTotal() {
        return total;
    }
    public void setTotal(Integer total) {
        this.total = total;
    }
    public Car getCar() {
        return car;
    }
    public void setCar(Car car) {
        this.car = car;
    }
    public PickUpPoint getPickuppoint() {
        return pickuppoint;
    }
    public void setPickuppoint(PickUpPoint pickuppoint) {
        this.pickuppoint = pickuppoint;
    }
    public Customer getCustomer() {
        return customer;
    }
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * Create a human readable serialization.
     */
    public String toString() {
        String result = "{ RentalID: " + this.rentalId + ", Date:'" + this.rentaldate +", RentalFrom " + this.rentalfrom
                + "RentalTo: " + this.rentalto +"Discount: " +this.discount+ "DeliveratothePoint: "
                +this.deliverytothepoint +"DeliveryAddress:" +this.deliveryaddress + "Total:" +this.total
                + "Car: "+ this.car + "PickupPoint: "+ this.pickuppoint + "Customer: " +this.customer;
        return result;
    }

    @Override
    public boolean equals( Object obj) {
        if (obj instanceof Rental) {
            Rental rental = (Rental) obj;
            return ( this.rentalId.equals( rental.rentalId));
        } else return false;
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws UniquenessConstraintViolation
     */
    public static void checkRentalIdAsId( EntityManager em, Integer rentalId)
            throws UniquenessConstraintViolation,
            IntervalConstraintViolation {
        if (rentalId < 0) {
            throw new IntervalConstraintViolation(
                    "RentalId must be at least 0");
        } else {
            Rental rental = Rental.retrieve( em, rentalId);
            // car was found, uniqueness constraint validation failed
            if ( rental != null) {
                throw new UniquenessConstraintViolation(
                        "There is already a Rental record with this rentalId!");
            }
        }
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkRentalDate( EntityManager em, Date rentaldate)
            throws IntervalConstraintViolation, ParseException {
        if ( rentaldate.before(new Date())) {
            throw new IntervalConstraintViolation(
                    "The rental cannot be in the past");
        }
    }
    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkRentalFrom( EntityManager em, Date rentalfrom)
            throws IntervalConstraintViolation, ParseException {
        if ( rentalfrom.before(new Date())) {
            throw new IntervalConstraintViolation(
                    "The rental cannot be in the past");
        }
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkRentalTo( EntityManager em, Date rentalto)
            throws IntervalConstraintViolation, ParseException {
        if ( rentalto.before(new Date())) {
            throw new IntervalConstraintViolation(
                    "The rental cannot be in the past");
        }
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkDiscount( EntityManager em, Integer discount)
            throws IntervalConstraintViolation {
        if ( discount < 0) {
            throw new IntervalConstraintViolation(
                    "Discount cant be lower than zero");
        }
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkDeliverytothepoint( EntityManager em, boolean deliverytothepoint)
            throws IntervalConstraintViolation {
        if ( deliverytothepoint) {
            throw new IntervalConstraintViolation(
                    "Discount cant be lower than zero");
        }
    }


    public static void checkDeliveryaddress( EntityManager em, String deliveryaddress)
            throws MandatoryValueConstraintViolation {
        if (deliveryaddress == null) {
            throw new MandatoryValueConstraintViolation(
                    "Car Name is mandatory");
        }
    }

    /**
     * Check for the carId uniqueness constraint by verifying the existence in the
     * database of a car entry for the given carId value.
     *
     * @throws IntervalConstraintViolation
     */
    public static void checkTotal( EntityManager em, Integer total)
            throws IntervalConstraintViolation {
        if ( total < 0) {
            throw new IntervalConstraintViolation(
                    "The car has rentalto have at least 1hp power");
        }
    }


    // CRUD data management methods
    public static void create(EntityManager em, UserTransaction ut,
                              Integer rentalId, Date rentaldate, Date rentalfrom, Date rentalto, Integer discount,
                              boolean deliverytothepoint, String deliveryaddress, Integer total, Car car,
                              PickUpPoint pickuppoint, Customer customer)
            throws Exception {
        ut.begin();
        Rental rental = new Rental( rentalId, rentaldate, rentalfrom, rentalto, discount, deliverytothepoint,
                deliveryaddress, total, car, pickuppoint, customer);
        em.persist( rental);
        ut.commit();
    }

    public static List<Rental> retrieveAll(EntityManager em) {
        Query query = em.createQuery( "SELECT r FROM Rental r", Rental.class);
        List<Rental> rentals = query.getResultList();
        return rentals;
    }

    public static Rental retrieve(EntityManager em, Integer rentalId) {
        Rental rental = em.find( Rental.class, rentalId);
        if ( rental != null) {
            System.out.println( "Rental.retrieve: loaded rental " + rental);
        }
        return rental;
    }
    public static void update( EntityManager em,

src/dresden23/ctrl/rentalController.java
package dresden23.ctrl;

import dresden23.model.Car;
import dresden23.model.Customer;
import dresden23.model.PickUpPoint;
import dresden23.model.Rental;
import org.apache.openjpa.persistence.EntityExistsException;

import javax.annotation.Resource;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.*;
import java.util.Date;
import java.util.List;

@SessionScoped @ManagedBean( name="rentalCtrl")

public class rentalController {
    @PersistenceContext( unitName="webapp")
    private EntityManager em;
    @Resource UserTransaction ut;




//    EntityManagerFactory emf =
//            Persistence.createEntityManagerFactory("webapp");
//    EntityManager em = emf.createEntityManager();
//    EntityTransaction et = em.getTransaction();
    /**
     * Read the list of all the rentals rentalfrom the database.
     *
     * @return a list with all the Rental instance found in the database.
     */
    public List<Rental> getRentals() {
        return Rental.retrieveAll( em);
    }
    /**
     * Update the reference object by setting its property values rentalto match the one
     * existing in the database for the specific instance, identified by the
     * primary key value.
     *
     * @param rental
     *          the reference rentalto the Rental instance rentalto be "loaded" rentalfrom database.
     */
    public void refreshObjects( Rental rental) {
        Rental foundRental = Rental.retrieve( em, rental.getRentalId());
        rental.setRentaldate( foundRental.getRentaldate());
        rental.setRentalfrom( foundRental.getRentalfrom());
        rental.setRentalto( foundRental.getRentalto());
        rental.setDiscount( foundRental.getDiscount());
        rental.setDeliveryToThePoint( foundRental.getDeliveryToThePoint());
        rental.setDeliveryaddress( foundRental.getDeliveryaddress());
        rental.setTotal( foundRental.getTotal());
        rental.setCar(foundRental.getCar());
        rental.setPickuppoint(foundRental.getPickuppoint());
        rental.setCustomer(foundRental.getCustomer());
    }
    /**
     * Create and persist a new Rental instance.
     *
     * @param rentalId
     *          the rentalId of the rental rentalto create
     * @return a string representing the view name rentalto display after finishing the
     *         execution of this method.
     */

    public String create(Integer rentalId, Date rentaldate, Date rentalfrom, Date rentalto, Integer discount,
                         boolean deliverytothepoint, String deliveryaddress, Integer total, Car car,
                         PickUpPoint pickUpPoint, Customer customer) {
        try {
            Rental.create( em, ut, rentalId, rentaldate, rentalfrom, rentalto, discount, deliverytothepoint,
                    deliveryaddress, total, car, pickUpPoint, customer);
            // Enforce clearing the form after creating the Car row.
            // Without this, the form will show the latest completed data
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.getExternalContext().getRequestMap().remove( "rental");
        } catch ( EntityExistsException e) {
            try {
                ut.rollback();
            } catch ( Exception e1) {
                e1.printStackTrace();
            }
            e.printStackTrace();
        } catch ( Exception e) {
            e.printStackTrace();
        }
        return "create";
    }

    /**
     * Update a Rental instance.
     *
     * @param rentalId
     *          the rentalId of the rental rentalto update (the rental will be identified in the
     *          database by using this value)
     * @return a string representing the view name rentalto display after finishing the
     *         execution of this method.
     */

    public String update(Integer rentalId, Date rentaldate, Date rentalfrom, Date rentalto, Integer discount,
                         boolean deliverytothepoint, String deliveryaddress, Integer total, Car car,
                         PickUpPoint pickUpPoint, Customer customer) {
        try {
            Rental.update( em, ut, rentalId, rentaldate, rentalfrom, rentalto, discount, deliverytothepoint,
                    deliveryaddress, total, car, pickUpPoint, customer);
        } catch ( Exception e) {
            e.printStackTrace();
        }
        return "update";
    }
    /**
     * Delete a Rental entry rentalfrom database.
     *
     * @param rentalId
     *          the rentalId of the rental rentalto delete - used rentalto uniquely identify the
     *          rental entry.
     * @return a string representing the view name rentalto display after finishing the
     *         execution of this method.
     */
    public String delete( Integer rentalId) {    try {
        Rental.delete( em, ut, rentalId);
        } catch ( Exception e) {
            e.printStackTrace();
        }
        return "delete";
    }
    /**
     * Clear/delete all entries rentalfrom the <code>books</code> table
     *
     * @return a string representing the view name rentalto display after finishing the
     *         execution of this method.
     *
     * @throws NotSupportedException
     * @throws SystemException
     * @throws IllegalStateException
     * @throws SecurityException
     * @throws HeuristicMixedException
     * @throws HeuristicRollbackException
     * @throws RollbackException
     */
    public String clearData() {
        try {
            Rental.clearData( em, ut);
        } catch ( Exception e) {
            e.printStackTrace();
        }
        return "index";
    }

    /**
     * Create test data (rows) in the <code>books</code> table
     *
     * @return a string representing the view name rentalto display after finishing the
     *         execution of this method.
     *
     * @throws NotSupportedException
     * @throws SystemException
     * @throws IllegalStateException
     * @throws SecurityException
     * @throws HeuristicMixedException
     * @throws HeuristicRollbackException
     * @throws RollbackException
     */
//    public String createTestData() {
//        try {
//            Rental.generateTestData( em, ut);
//        } catch ( Exception e) {
//            e.printStackTrace();
//        }
//        return "index";
//    }




}

web/views/rentals/create.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="createRentalForm" styleClass="clearfix" >
        <h:panelGrid id="rentalPanel" columns="3">
          <h:outputLabel for="rentalId" value="RentalId: " />
          <h:inputText id="rentalId" value="#{rental.rentalId}"
                       validator="#{rentalCtrl.checkRentalIdAsId}" />
          <h:message for="rentalId" errorClass="error" />
          <h:outputLabel for="rentalfrom" value="From: " />
          <h:inputText id="rentalfrom" p:type="date" value="#{rental.rentalfrom}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"/>
          </h:inputText>
          <h:message for="rentalfrom" errorClass="error" />
          <h:outputLabel for="rentalto" value="To: " />
          <h:inputText id="rentalto" p:type="date" value="#{rental.rentalto}">
            <f:convertDateTime type="date" dateStyle="short" pattern="yyyy-MM-dd"/>
          </h:inputText>
          <h:message for="rentalto" errorClass="error" />
          <h:outputLabel for="discount" value="Discount: " />
          <h:inputText id="discount" value="#{rental.discount}"
                       validator="#{rentalCtrl.checkDiscount}" />
          <h:message for="discount" errorClass="error" />
          <h:outputLabel for="deliverytothepoint" value="DeliveryToThePoint?: " />
          <h:selectBooleanCheckbox id="deliverytothepoint" value="#{rental.deliveryToThePoint}" /> DeliveryTothePoint
            <f:ajax event="click" execute="@this"
                    render="pickuppointPanel" hide="deliverytoaddressPanel"/>
          <h:message for="deliverytothepoint" errorClass="error" />

          <h:panelGroup id="deliverytoaddressPanel">
            <h:panelGrid rendered="#{viewScope.deliverytothepoint == 'ON'}" columns="3">
            <h:outputLabel for="deliveryaddress" value="DeliveryAddress: " />
            <h:inputText id="deliveryaddress" value="#{rental.deliveryaddress}"/>
            <h:message for="deliveryaddress" errorClass="error" />
            </h:panelGrid>
          </h:panelGroup>
          <h:panelGroup id="pickuppointPanel" rendered="false">
            <h:panelGrid rendered="#{viewScope.deliverytothepoint == 'OFF'}" columns="3">
              <h:selectOneMenu id="pickuppoint" value="#{rental.pickuppoint}">
                <f:selectItem itemLabel="---"/>
                <f:selectItems value="#{pickuppointCtrl.pickuppoints}" />
              </h:selectOneMenu>
              <h:message for="pickuppoint" errorClass="error" />
            </h:panelGrid>
          </h:panelGroup>
          <h:outputLabel for="total" value="Total: " />
          <h:inputText id="total" value="#{rental.total}" />
          <h:message for="total" errorClass="error" />
          <h:commandButton value="Create"
                           action="#{rentalCtrl.create( rental.rentalId, rental.rentaldate, rental.rentalfrom,
                             rental.rentalto, rental.discount, rental.deliveryToThePoint, rental.deliveryaddress,
                             rental.total, rental.car, rental.pickuppoint, rental.customer)}" />
        </h:panelGrid>
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/rentals/delete.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="deleteBookForm" styleClass="pure-form pure-form-aligned">
        <h:panelGrid columns="2">
          <h:outputLabel for="selectBook" value="Select book: " />
          <h:selectOneMenu id="selectBook" value="#{book.isbn}">
            <f:selectItems value="#{bookCtrl.books}" var="b"
              itemValue="#{b.isbn}" itemLabel="#{b.title}" />
          </h:selectOneMenu>
        </h:panelGrid>
        <h:commandButton value="Delete"
          action="#{bookCtrl.destroy( book.isbn)}" />
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/rentals/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h2>Manage Rental entries:</h2>
      <h:button value="List all rentals" outcome="listAll" />
      <h:button value="Add a new Rental" outcome="create" />
      <h:button value="Update a Rental" outcome="update" />
      <h:button value="Delete a Rental" outcome="delete" />
      <h:button value="Main menu" outcome="/views/app/index" />
    </ui:define>
  </ui:composition>
</html>

web/views/rentals/listAll.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:dataTable value="#{bookCtrl.books}" var="b">
        <h:column>
          <f:facet name="header">ISBN</f:facet>
            #{b.isbn}
        </h:column>
        <h:column>
          <f:facet name="header">Title</f:facet>
            #{b.title}
          </h:column>
        <h:column>
          <f:facet name="header">Year</f:facet>
            #{b.year}
        </h:column>
        <h:column>
          <f:facet name="header">Special type</f:facet>
            #{b.getClass().getSimpleName() != 'Book' ? b.getClass().getSimpleName() : ''}
        </h:column>
      </h:dataTable>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>

web/views/rentals/update.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

  <ui:composition template="/WEB-INF/templates/page.xhtml">
    <ui:define name="main">
      <h:form id="createBookForm" styleClass="pure-form pure-form-aligned">
        <h:panelGrid id="bookPanel" columns="3">
          <h:outputLabel for="selectBook" value="Select book: " />
          <h:selectOneMenu id="selectBook" value="#{book.isbn}">
            <f:selectItem itemValue="" itemLabel="---" />
            <f:selectItems value="#{bookCtrl.books}" var="b"
              itemValue="#{b.isbn}" itemLabel="#{b.title}" />
            <f:ajax listener="#{bookCtrl.refreshObjects()}"
              render="isbn title year textBookPanel biographyBookPanel standardBookPanel bookType" />
          </h:selectOneMenu>
          <h:message for="selectBook" />
          <h:outputLabel for="isbn" value="ISBN: " />
          <h:outputText id="isbn" value="#{book.isbn}" />
          <h:message for="isbn" />
          <h:outputLabel for="title" value="Title: " />
          <h:inputText id="title" value="#{book.title}" />
          <h:message for="title" errorClass="error" />
          <h:outputLabel for="year" value="Year: " />
          <h:inputText id="year" p:type="number" value="#{book.year}" />
          <h:message for="year" errorClass="error" />
          <h:outputLabel for="bookType" value="Special type: " />
          <c:set var="selectedBookType" value="#{bookCtrl.getSelectedObjectType( book.isbn)}"/>
          <h:selectOneMenu id="bookType" value="#{selectedBookType}" disabled="true">
            <f:selectItem itemLabel="---"/>
            <f:selectItems value="#{book.typeItems}" />
            <f:ajax event="change" execute="@this" 
              render="textBookPanel biographyBookPanel standardBookPanel" />
          </h:selectOneMenu>
          <h:message for="bookType" errorClass="error" />
        </h:panelGrid>
        
        <h:panelGroup id="standardBookPanel">  
          <h:commandButton value="Update" rendered="#{selectedBookType == null}"
            action="#{bookCtrl.update( book.isbn, book.title, book.year)}" />
        </h:panelGroup>
        
        <h:panelGroup id="textBookPanel">  
          <h:panelGrid rendered="#{selectedBookType == 'TEXTBOOK'}" columns="3">
            <h:outputLabel for="subjectArea" value="Subject area: " />
            <h:inputText id="subjectArea" value="#{textBook.subjectArea}"/>
            <h:message for="subjectArea" errorClass="error" />
          </h:panelGrid>
          <h:commandButton value="Update" rendered="#{selectedBookType == 'TEXTBOOK'}"
            action="#{textBookCtrl.update( book.isbn, book.title, book.year, textBook.subjectArea)}" />
        </h:panelGroup>
        
        <h:panelGroup id="biographyBookPanel">  
          <h:panelGrid rendered="#{selectedBookType == 'BIOGRAPHY'}" columns="3">
            <h:outputLabel for="about" value="About: " />
            <h:inputText id="about" value="#{biographyBook.about}"/>
            <h:message for="about" errorClass="error" />
          </h:panelGrid>
          <h:commandButton value="Update" rendered="#{selectedBookType == 'BIOGRAPHY'}"
            action="#{biographyCtrl.update( book.isbn, book.title, book.year, biographyBook.about)}" />
        </h:panelGroup>
      </h:form>
      <h:button value="Back" outcome="index" />
    </ui:define>
  </ui:composition>
</html>